plugins { id 'com.android.application'; id 'org.jetbrains.kotlin.android' }
android {
    namespace 'com.neyman.radio_player'
    compileSdk 34
    
    signingConfigs {
        release {
            storeFile file("keystore.jks")
            storePassword "password"
            keyAlias "my-alias"
            keyPassword "password"
        }
    }

    defaultConfig {
        applicationId "com.neyman.radio_player"
        minSdk 24
        targetSdk 34
        versionCode 4
        versionName "1.3"
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    kotlinOptions { jvmTarget = '17' }
    
    buildTypes {
        debug { signingConfig signingConfigs.release }
        release { signingConfig signingConfigs.release }
    }
}
dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.media3:media3-exoplayer:1.2.0'
    implementation 'androidx.media3:media3-exoplayer-hls:1.2.0'
    implementation 'androidx.media3:media3-session:1.2.0'
    implementation 'com.google.guava:guava:31.1-android'
}